"""
SQLite schema for Pathosphere.

Tables:
  sources          — source catalogue (country, orientation, state control)
  raw_documents    — raw ingested documents
  events           — aggregated events (article clusters)
  entities         — extracted entities (countries, companies, commodities, infrastructure)
  entity_links     — entity relations (graph)
  theses           — theses generated by the agent
  trades           — paper trading operations
  portfolios       — virtual portfolios (agent, random, benchmark)
  predictions      — non-financial forecasts with Tetlock calibration

sqlite-vec: virtual table vec_documents for nearest-neighbour on embeddings.
"""

import sqlite3
from pathlib import Path

import sqlite_vec

DDL = """
PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

-- ──────────────────────────────────────────────
-- SOURCES
-- ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sources (
    id              INTEGER PRIMARY KEY,
    name            TEXT    NOT NULL UNIQUE,
    url             TEXT,
    country         TEXT    NOT NULL,           -- ISO 3166-1 alpha-2
    geopolitical_block TEXT NOT NULL,           -- western, china, russia, arab, india, latam, africa, other
    orientation     TEXT,                       -- e.g. state, independent, opposition
    state_control   INTEGER NOT NULL DEFAULT 0, -- 0-3 (0=none, 3=full)
    language        TEXT,                       -- ISO 639-1
    active          INTEGER NOT NULL DEFAULT 1,
    notes           TEXT,
    created_at      TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- ──────────────────────────────────────────────
-- RAW DOCUMENTS
-- ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS raw_documents (
    id              INTEGER PRIMARY KEY,
    source_id       INTEGER REFERENCES sources(id),
    origin          TEXT,                       -- ingestor: gdelt|rss|comtrade|portwatch|usgs|firms
    url             TEXT    UNIQUE,
    title           TEXT,
    body            TEXT,
    published_at    TEXT,                       -- ISO 8601
    fetched_at      TEXT    NOT NULL DEFAULT (datetime('now')),
    language        TEXT,
    content_hash    TEXT    UNIQUE,             -- SHA-256 of body for exact dedup
    embedded        INTEGER NOT NULL DEFAULT 0, -- 0=not yet; 1=embedding computed
    is_duplicate    INTEGER NOT NULL DEFAULT 0, -- 1 = near-duplicate of another doc
    duplicate_of    INTEGER REFERENCES raw_documents(id),
    dedup_checked   INTEGER NOT NULL DEFAULT 0, -- 1 after dedup phase ran on this doc
    ner_done        INTEGER NOT NULL DEFAULT 0  -- 1 after NER phase ran on this doc
);

CREATE INDEX IF NOT EXISTS idx_raw_doc_source    ON raw_documents(source_id);
CREATE INDEX IF NOT EXISTS idx_raw_doc_published ON raw_documents(published_at);
CREATE INDEX IF NOT EXISTS idx_raw_doc_embedded  ON raw_documents(embedded);
CREATE INDEX IF NOT EXISTS idx_raw_doc_dedup     ON raw_documents(is_duplicate, dedup_checked);

-- ──────────────────────────────────────────────
-- EVENTS (article clusters)
-- ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS events (
    id              INTEGER PRIMARY KEY,
    title           TEXT    NOT NULL,
    summary         TEXT,
    first_seen      TEXT    NOT NULL,
    last_seen       TEXT    NOT NULL,
    event_type      TEXT,                       -- conflict, epidemic, trade, infrastructure, political, other
    origin          TEXT,                       -- ingestor: gdelt|rss|comtrade|portwatch|usgs|firms
    severity        INTEGER,                    -- 1-5
    location_name   TEXT,
    lat             REAL,
    lon             REAL,
    resolved_at     TEXT,
    created_at      TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_events_title ON events(title);

CREATE TABLE IF NOT EXISTS event_documents (
    event_id        INTEGER REFERENCES events(id) ON DELETE CASCADE,
    document_id     INTEGER REFERENCES raw_documents(id) ON DELETE CASCADE,
    PRIMARY KEY (event_id, document_id)
);

-- ──────────────────────────────────────────────
-- GDELT EVENT DETAIL (one row per GDELT GlobalEventID)
-- ──────────────────────────────────────────────
-- Full numeric fidelity per raw GDELT row, linked to our coarse 5-tuple
-- `events` cluster and to the source document. Goldstein/tone/mention signals
-- live here at GlobalEventID granularity and can be aggregated up to events.
CREATE TABLE IF NOT EXISTS gdelt_events (
    global_event_id INTEGER PRIMARY KEY,         -- GDELT GlobalEventID (unique per row)
    event_id        INTEGER REFERENCES events(id) ON DELETE CASCADE,
    document_id     INTEGER REFERENCES raw_documents(id) ON DELETE CASCADE,
    sqldate         TEXT,                         -- raw SQLDATE (unreliable; kept for audit)
    date_added      TEXT,                         -- DATEADDED → ISO (canonical observation date)
    event_code      TEXT,                         -- full CAMEO EventCode
    event_root_code TEXT,                         -- CAMEO root (maps to events.event_type)
    quad_class      INTEGER,                      -- 1 verbal-coop, 2 material-coop, 3 verbal-conflict, 4 material-conflict
    goldstein       REAL,                         -- -10..+10 theoretical impact
    avg_tone        REAL,                         -- average article tone
    num_mentions    INTEGER,
    num_sources     INTEGER,
    num_articles    INTEGER
);

CREATE INDEX IF NOT EXISTS idx_gdelt_ev_event ON gdelt_events(event_id);
CREATE INDEX IF NOT EXISTS idx_gdelt_ev_date  ON gdelt_events(date_added);

-- Narrative divergence per event (comparison across geopolitical blocks)
CREATE TABLE IF NOT EXISTS narrative_divergences (
    id              INTEGER PRIMARY KEY,
    event_id        INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    block_a         TEXT    NOT NULL,
    block_b         TEXT    NOT NULL,
    divergence_score REAL,                      -- 0-1
    summary         TEXT,
    computed_at     TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- ──────────────────────────────────────────────
-- ENTITIES AND GRAPH
-- ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS entities (
    id              INTEGER PRIMARY KEY,
    name            TEXT    NOT NULL,
    canonical_name  TEXT,
    entity_type     TEXT    NOT NULL,           -- country, company, commodity, infrastructure, person, other
    wikidata_qid    TEXT    UNIQUE,
    wikidata_checked INTEGER NOT NULL DEFAULT 0, -- 1 after Wikidata lookup attempted
    aliases         TEXT,                       -- JSON array
    created_at      TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_entity_type ON entities(entity_type);
CREATE INDEX IF NOT EXISTS idx_entity_qid  ON entities(wikidata_qid);

CREATE TABLE IF NOT EXISTS entity_links (
    id              INTEGER PRIMARY KEY,
    entity_a        INTEGER NOT NULL REFERENCES entities(id),
    entity_b        INTEGER NOT NULL REFERENCES entities(id),
    relation_type   TEXT    NOT NULL,           -- depends_on, supplies, sanctions, ally, adversary, ...
    strength        REAL,                       -- 0-1
    source_event    INTEGER REFERENCES events(id),
    valid_from      TEXT,
    valid_to        TEXT,
    notes           TEXT
);

CREATE INDEX IF NOT EXISTS idx_elink_a ON entity_links(entity_a);
CREATE INDEX IF NOT EXISTS idx_elink_b ON entity_links(entity_b);

-- Entity mentions per document (NER output)
CREATE TABLE IF NOT EXISTS document_entities (
    document_id     INTEGER REFERENCES raw_documents(id) ON DELETE CASCADE,
    entity_id       INTEGER REFERENCES entities(id) ON DELETE CASCADE,
    mentions        INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (document_id, entity_id)
);

CREATE INDEX IF NOT EXISTS idx_docent_entity ON document_entities(entity_id);

-- Nominatim lookup cache (misses cached with NULL lat/lon)
CREATE TABLE IF NOT EXISTS geocode_cache (
    query           TEXT    PRIMARY KEY,
    lat             REAL,
    lon             REAL,
    display_name    TEXT,
    fetched_at      TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- ──────────────────────────────────────────────
-- PORTWATCH (daily chokepoint transit timeseries)
-- ──────────────────────────────────────────────
-- Raw daily counts per chokepoint; anomalies vs trailing baseline are
-- promoted to events (event_type=infrastructure). Baseline is computed
-- from this table only — no lookahead.
CREATE TABLE IF NOT EXISTS chokepoint_metrics (
    portid          TEXT    NOT NULL,            -- e.g. chokepoint1
    portname        TEXT,                        -- e.g. Suez Canal
    date            TEXT    NOT NULL,            -- ISO YYYY-MM-DD
    n_total         INTEGER,
    n_tanker        INTEGER,
    n_container     INTEGER,
    n_dry_bulk      INTEGER,
    n_cargo         INTEGER,
    capacity        REAL,
    fetched_at      TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (portid, date)
);

CREATE INDEX IF NOT EXISTS idx_chokepoint_date ON chokepoint_metrics(portid, date);

-- ──────────────────────────────────────────────
-- COMTRADE (monthly trade-flow numeric detail)
-- ──────────────────────────────────────────────
-- Numeric trade values per (reporter, partner, commodity, flow, period),
-- alongside the synthetic raw_document. Keyed by document_id so each flow row
-- ties back to its document; period is YYYYMM.
CREATE TABLE IF NOT EXISTS comtrade_flows (
    id              INTEGER PRIMARY KEY,
    document_id     INTEGER REFERENCES raw_documents(id) ON DELETE CASCADE,
    reporter_code   INTEGER,                      -- ISO numeric reporter
    reporter_iso    TEXT,
    partner_code    INTEGER,                      -- 0 = World
    cmd_code        TEXT,                         -- HS code (8541/8542/8486)
    flow_code       TEXT,                         -- M import / X export
    period          TEXT,                         -- YYYYMM
    primary_value   REAL,                         -- trade value (USD)
    net_weight      REAL,                         -- kg, when present
    UNIQUE (reporter_code, cmd_code, flow_code, period, partner_code)
);

CREATE INDEX IF NOT EXISTS idx_comtrade_period ON comtrade_flows(period);
CREATE INDEX IF NOT EXISTS idx_comtrade_cmd    ON comtrade_flows(cmd_code, flow_code);

-- ──────────────────────────────────────────────
-- WATCHLIST (observable indicators per scenario)
-- ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS watchlist_items (
    id              INTEGER PRIMARY KEY,
    label           TEXT    NOT NULL,
    description     TEXT,
    indicator_query TEXT,                       -- keyword/GDELT filter
    status          TEXT    NOT NULL DEFAULT 'active',  -- active, triggered, expired
    triggered_at    TEXT,
    created_at      TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- ──────────────────────────────────────────────
-- AGENT THESES
-- ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS theses (
    id              INTEGER PRIMARY KEY,
    trigger_event   INTEGER REFERENCES events(id),
    title           TEXT    NOT NULL,
    causal_chain    TEXT    NOT NULL,           -- free text / JSON
    instrument      TEXT,                       -- e.g. "USO", "TSMC", "GLD"
    direction       TEXT,                       -- long / short / neutral
    horizon_days    INTEGER,
    invalidation    TEXT,
    confidence      REAL,                       -- 0-1 subjective
    status          TEXT    NOT NULL DEFAULT 'pending',  -- pending, approved, rejected, closed
    approved_at     TEXT,
    rejected_at     TEXT,
    rejection_reason TEXT,
    sources_json    TEXT,                       -- JSON array of URLs
    created_at      TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- ──────────────────────────────────────────────
-- PAPER TRADING
-- ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS portfolios (
    id              INTEGER PRIMARY KEY,
    name            TEXT    NOT NULL UNIQUE,    -- agent, random, benchmark
    portfolio_type  TEXT    NOT NULL,
    cash            REAL    NOT NULL DEFAULT 100000.0,
    created_at      TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS trades (
    id              INTEGER PRIMARY KEY,
    portfolio_id    INTEGER NOT NULL REFERENCES portfolios(id),
    thesis_id       INTEGER REFERENCES theses(id),
    ticker          TEXT    NOT NULL,
    direction       TEXT    NOT NULL,           -- buy / sell
    quantity        REAL    NOT NULL,
    price_open      REAL    NOT NULL,           -- price at DECISION time (no lookahead)
    price_close     REAL,                       -- price at close
    opened_at       TEXT    NOT NULL,
    closed_at       TEXT,
    transaction_cost REAL   NOT NULL DEFAULT 0.0,
    slippage        REAL    NOT NULL DEFAULT 0.0,
    pnl             REAL,                       -- computed at close
    notes           TEXT
);

CREATE INDEX IF NOT EXISTS idx_trade_portfolio ON trades(portfolio_id);
CREATE INDEX IF NOT EXISTS idx_trade_ticker    ON trades(ticker);

-- ──────────────────────────────────────────────
-- NON-FINANCIAL PREDICTIONS (Tetlock calibration)
-- ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS predictions (
    id              INTEGER PRIMARY KEY,
    thesis_id       INTEGER REFERENCES theses(id),
    description     TEXT    NOT NULL,           -- "Escalation in X within 2 weeks"
    probability     REAL    NOT NULL,           -- 0-1
    horizon_date    TEXT    NOT NULL,           -- deadline ISO 8601
    resolved        INTEGER NOT NULL DEFAULT 0, -- 0=open, 1=resolved
    outcome         INTEGER,                    -- NULL=open, 1=true, 0=false
    resolved_at     TEXT,
    brier_score     REAL,                       -- computed at resolution
    created_at      TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_pred_horizon  ON predictions(horizon_date);
CREATE INDEX IF NOT EXISTS idx_pred_resolved ON predictions(resolved);
"""

DDL += """
-- ──────────────────────────────────────────────
-- GDELT DOWNLOAD TRACKING
-- ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS gdelt_file_log (
    id              INTEGER PRIMARY KEY,
    filename        TEXT    NOT NULL UNIQUE,    -- e.g. 20260611153000.export.CSV.zip
    url             TEXT    NOT NULL,
    downloaded_at   TEXT    NOT NULL DEFAULT (datetime('now')),
    rows_raw        INTEGER,                    -- rows in the original CSV
    rows_stored     INTEGER,                    -- rows effectively inserted after filter
    status          TEXT    NOT NULL DEFAULT 'ok'  -- ok, error, skipped
);
"""

SQLITE_VEC_VIRTUAL = """
CREATE VIRTUAL TABLE IF NOT EXISTS vec_documents
USING vec0(
    document_id INTEGER PRIMARY KEY,
    embedding   FLOAT[384]          -- multilingual-e5-small output dim
);
"""


_MIGRATIONS = [
    "ALTER TABLE raw_documents ADD COLUMN is_duplicate INTEGER NOT NULL DEFAULT 0",
    "ALTER TABLE raw_documents ADD COLUMN duplicate_of INTEGER REFERENCES raw_documents(id)",
    "ALTER TABLE raw_documents ADD COLUMN dedup_checked INTEGER NOT NULL DEFAULT 0",
    "ALTER TABLE raw_documents ADD COLUMN ner_done INTEGER NOT NULL DEFAULT 0",
    "ALTER TABLE entities ADD COLUMN wikidata_checked INTEGER NOT NULL DEFAULT 0",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_entity_name_type ON entities(name, entity_type)",
    "CREATE INDEX IF NOT EXISTS idx_raw_doc_ner ON raw_documents(ner_done)",
    "ALTER TABLE raw_documents ADD COLUMN origin TEXT",
    "ALTER TABLE events ADD COLUMN origin TEXT",
]


def migrate_db(conn: sqlite3.Connection) -> None:
    """Apply schema migrations idempotently (safe to run on every init)."""
    for sql in _MIGRATIONS:
        try:
            conn.execute(sql)
            conn.commit()
        except sqlite3.OperationalError:
            pass  # column or index already exists


def get_connection(db_path: Path) -> sqlite3.Connection:
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    conn.enable_load_extension(True)
    sqlite_vec.load(conn)
    conn.enable_load_extension(False)
    conn.execute("PRAGMA journal_mode = WAL")
    conn.execute("PRAGMA busy_timeout = 30000")
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def init_db(db_path: Path) -> None:
    conn = get_connection(db_path)
    # Pre-migrate so column-adding ALTERs land before DDL indexes that
    # reference the new columns (e.g. idx_raw_doc_dedup on is_duplicate).
    # On a fresh DB these ALTERs no-op (tables absent) and DDL creates
    # everything; the post-DDL pass then adds migration-only indexes.
    migrate_db(conn)
    with conn:
        conn.executescript(DDL)
        conn.executescript(SQLITE_VEC_VIRTUAL)
    migrate_db(conn)
    conn.close()
